In [2]:
%cd drive/MyDrive/COS484

/content/drive/MyDrive/COS484


In [ ]:
!pip install transformers
!pip install nltk
!pip install fasttext

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 59.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 27.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 106.1 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.8/68.8 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
  Created wheel for fasttext: filename=fasttext-0.9.2-cp310-cp310-linux_x86_64.whl size=4393339 sha256=023e05bab666bb2276cf238ff7bb907fcfbb725437cd9b61a149741e925f3582
  Stored in directory: /root/.cache/pip/wheels/a5/13/75/f811c84a8ab36eedbaef977a6a58a98990e8e0f1967f98f394
Successful

In [13]:
import torch
train_labels = torch.load("disease/train_labels.bin")
test_labels = torch.load("disease/test_labels.bin")
dev_labels = torch.load("disease/dev_labels.bin")

In [15]:
print(train_labels.unique(return_counts=True))
print(test_labels.unique(return_counts=True))
print(dev_labels.unique(return_counts=True))

(tensor([0, 1]), tensor([1392, 5275]))
(tensor([0, 1]), tensor([ 936, 3165]))
(tensor([0, 1]), tensor([159, 614]))


In [ ]:
!python create_features.py --exp_config generator_config/wordtovec_exp_config.yaml

Exception ignored in: <function _xla_gc_callback at 0x7f48132fb490>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/lib/__init__.py", line 97, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt: 
2023-05-03 17:18:39.105334: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
^C


In [ ]:
!python run.py --data_dir disease --seed 65 --train --num_train_epochs 100 --task_name disease --classifier_type feature_concat --exp_dir new_features/disease-electramed-noexp-ameya --num_classes 2 --train_distributed 0 --dev_distributed 0 --save_model --output_dir outputs/disease-electramed-noexp-ameya --feature_dim 768

Namespace(train=True, eval=False, seed=1102, data_dir='combined/spouse', output_dir='checkpoints/spouse_expbert', exp_dir='expbert-features', feat_dir='', percent_train=1.0, train_distributed=10, dev_distributed=0, num_classes=2, train_file='train.txt', dev_file='dev.txt', hidden_dim=64, num_layers=0, dropout=0.0, feature_dim=768, projection_dim=64, hyperparam_config='', learning_rate=0.001, train_batch_size=32, num_train_epochs=100, max_grad_norm=10.0, weight_decay=0.0, classifier_type='feature_concat', task_name='spouse', save_model=True, exp_list=[], keep=False, device=device(type='cpu'), n_gpu=0, num_explanations=41, regex_features=0, train_bin_file=['expbert-features/train_0.bin', 'expbert-features/train_1.bin', 'expbert-features/train_2.bin', 'expbert-features/train_3.bin', 'expbert-features/train_4.bin', 'expbert-features/train_5.bin', 'expbert-features/train_6.bin', 'expbert-features/train_7.bin', 'expbert-features/train_8.bin', 'expbert-features/train_9.bin'], dev_bin_file='ex

In [ ]:
!python run.py --data_dir disease --seed 60 --train --num_train_epochs 100 --task_name disease --classifier_type feature_concat --exp_dir new_features/disease-electramed-noexp-ameya --num_classes 2 --train_distributed 0 --dev_distributed 0 --save_model --output_dir outputs/disease-electramed-noexp-ameya --feature_dim 768

Namespace(train=True, eval=False, seed=1102, data_dir='combined/spouse', output_dir='checkpoints/spouse_expbert', exp_dir='expbert-features', feat_dir='', percent_train=1.0, train_distributed=10, dev_distributed=0, num_classes=2, train_file='train.txt', dev_file='dev.txt', hidden_dim=64, num_layers=0, dropout=0.0, feature_dim=768, projection_dim=64, hyperparam_config='', learning_rate=0.001, train_batch_size=32, num_train_epochs=100, max_grad_norm=10.0, weight_decay=0.0, classifier_type='feature_concat', task_name='spouse', save_model=True, exp_list=[], keep=False, device=device(type='cpu'), n_gpu=0, num_explanations=41, regex_features=0, train_bin_file=['expbert-features/train_0.bin', 'expbert-features/train_1.bin', 'expbert-features/train_2.bin', 'expbert-features/train_3.bin', 'expbert-features/train_4.bin', 'expbert-features/train_5.bin', 'expbert-features/train_6.bin', 'expbert-features/train_7.bin', 'expbert-features/train_8.bin', 'expbert-features/train_9.bin'], dev_bin_file='ex

In [ ]:
!python run.py --data_dir disease --seed 55 --train --num_train_epochs 100 --task_name disease --classifier_type feature_concat --exp_dir new_features/disease-electramed-noexp-ameya --num_classes 2 --train_distributed 0 --dev_distributed 0 --save_model --output_dir outputs/disease-electramed-noexp-ameya --feature_dim 768

Namespace(train=True, eval=False, seed=1102, data_dir='combined/spouse', output_dir='checkpoints/spouse_expbert', exp_dir='expbert-features', feat_dir='', percent_train=1.0, train_distributed=10, dev_distributed=0, num_classes=2, train_file='train.txt', dev_file='dev.txt', hidden_dim=64, num_layers=0, dropout=0.0, feature_dim=768, projection_dim=64, hyperparam_config='', learning_rate=0.001, train_batch_size=32, num_train_epochs=100, max_grad_norm=10.0, weight_decay=0.0, classifier_type='feature_concat', task_name='spouse', save_model=True, exp_list=[], keep=False, device=device(type='cpu'), n_gpu=0, num_explanations=41, regex_features=0, train_bin_file=['expbert-features/train_0.bin', 'expbert-features/train_1.bin', 'expbert-features/train_2.bin', 'expbert-features/train_3.bin', 'expbert-features/train_4.bin', 'expbert-features/train_5.bin', 'expbert-features/train_6.bin', 'expbert-features/train_7.bin', 'expbert-features/train_8.bin', 'expbert-features/train_9.bin'], dev_bin_file='ex

In [ ]:
!python run.py --data_dir disease --seed 50 --train --num_train_epochs 100 --task_name disease --classifier_type feature_concat --exp_dir new_features/disease-electramed-noexp-ameya --num_classes 2 --train_distributed 0 --dev_distributed 0 --save_model --output_dir outputs/disease-electramed-noexp-ameya --feature_dim 768

Namespace(train=True, eval=False, seed=1102, data_dir='combined/spouse', output_dir='checkpoints/spouse_expbert', exp_dir='expbert-features', feat_dir='', percent_train=1.0, train_distributed=10, dev_distributed=0, num_classes=2, train_file='train.txt', dev_file='dev.txt', hidden_dim=64, num_layers=0, dropout=0.0, feature_dim=768, projection_dim=64, hyperparam_config='', learning_rate=0.001, train_batch_size=32, num_train_epochs=100, max_grad_norm=10.0, weight_decay=0.0, classifier_type='feature_concat', task_name='spouse', save_model=True, exp_list=[], keep=False, device=device(type='cpu'), n_gpu=0, num_explanations=41, regex_features=0, train_bin_file=['expbert-features/train_0.bin', 'expbert-features/train_1.bin', 'expbert-features/train_2.bin', 'expbert-features/train_3.bin', 'expbert-features/train_4.bin', 'expbert-features/train_5.bin', 'expbert-features/train_6.bin', 'expbert-features/train_7.bin', 'expbert-features/train_8.bin', 'expbert-features/train_9.bin'], dev_bin_file='ex

In [ ]:
!python run.py --data_dir disease --seed 45 --train --num_train_epochs 100 --task_name disease --classifier_type feature_concat --exp_dir new_features/disease-electramed-noexp-ameya --num_classes 2 --train_distributed 0 --dev_distributed 0 --save_model --output_dir outputs/disease-electramed-noexp-ameya --feature_dim 768

Namespace(train=True, eval=False, seed=1102, data_dir='combined/spouse', output_dir='checkpoints/spouse_expbert', exp_dir='expbert-features', feat_dir='', percent_train=1.0, train_distributed=10, dev_distributed=0, num_classes=2, train_file='train.txt', dev_file='dev.txt', hidden_dim=64, num_layers=0, dropout=0.0, feature_dim=768, projection_dim=64, hyperparam_config='', learning_rate=0.001, train_batch_size=32, num_train_epochs=100, max_grad_norm=10.0, weight_decay=0.0, classifier_type='feature_concat', task_name='spouse', save_model=True, exp_list=[], keep=False, device=device(type='cpu'), n_gpu=0, num_explanations=41, regex_features=0, train_bin_file=['expbert-features/train_0.bin', 'expbert-features/train_1.bin', 'expbert-features/train_2.bin', 'expbert-features/train_3.bin', 'expbert-features/train_4.bin', 'expbert-features/train_5.bin', 'expbert-features/train_6.bin', 'expbert-features/train_7.bin', 'expbert-features/train_8.bin', 'expbert-features/train_9.bin'], dev_bin_file='ex

In [ ]:
features = torch.load("disease/new_features/disease-bert-noexp-ameya/train.bin")